apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: grpc-book-demo-gcp
build:
  artifacts:
  - image: gcr.io/jfang-test/book-service
    context: book-service
    jib:
      project: book-app
  - image: gcr.io/jfang-test/book-web
    context: book-web
    jib: {}
deploy:
  kubectl:
    manifests:
    - kubernetes.yaml
